AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Bucket:
    Type: String
  Key:
    Type: String

Resources:

  ProductScraperRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        -
          PolicyName: ProfuctScraperPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              -
                Effect: Allow
                Action:
                   - s3:PutObject
                   - s3:PutObjectAcl
                Resource: !Sub 'arn:aws:s3:::${Bucket}/${Key}' 

  ProductScraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: periodic.lambda_handler
      Runtime: python3.12
      CodeUri: ./periodic
      Timeout: 60
      Role: !GetAtt [ProductScraperRole, Arn]
      Environment:
        Variables:
          bucket: !Ref Bucket
          key: !Ref Key

  ProductScraperSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: Monthly update on 1st day of month at 00:00 UTC
      ScheduleExpression: cron(0 0 1 * ? *)
      State: ENABLED
      Targets:
        -
          Arn: !GetAtt [ProductScraper, Arn]
          Id: TargetFunctionV1

  ProductScraperInvokePermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProductScraper
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [ProductScraperSchedule, Arn]
